---
kind: Service
apiVersion: v1
metadata:
  name: nfsserver
  namespace: shared-services
spec:
  type: NodePort
  selector:
    app: nfsserver
  ports:
    - protocol: TCP
      nodePort: 32049
      port: 2049
      name: nfsserver
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfsserver
  namespace: shared-services
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nfsserver
    spec:
      containers:
      - name: pgadmin
        image: "itsthenetwork/nfs-server-alpine:latest"
        # image: <repoURL>/nfsserver:<tagVersion>
        securityContext:
          privileged: true
        env:
          - name: "SHARED_DIRECTORY"
            value: "/var/exports"
          - name: "PERMITTED"
            value: "*"
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 300m
            memory: 500Mi
        ports:
        - containerPort: 2049
          name: nfsserver
        volumeMounts:
        - mountPath: /var/exports
          name: nfsserver-persistent-storage
      volumes:
      - name: nfsserver-persistent-storage
        persistentVolumeClaim:
          claimName: nfs-server-pv-claim
