---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/exports
  capacity:
    storage: 30Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-pv-claim
  namespace: shared-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 30Gi
